# Generated by Django 5.1.2 on 2024-10-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
