# Generated by Django 5.1.1 on 2024-09-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_tomatoes_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
