# Generated by Django 5.1.1 on 2024-10-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0004_studio_movie_art_movie_tagline_show_art_show_tagline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="absolute_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="added_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="audience_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="audience_rating_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="guid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="has_commercial_marker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="episode",
            name="has_credits_marker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="episode",
            name="has_intro_marker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="episode",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="originally_available_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="added_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="audience_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="audience_rating_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="chapter_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="edition_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="enable_credits_marker_generation",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="movie",
            name="guid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="original_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="originally_available_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="use_original_title",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="movie",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="show",
            name="added_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="audience_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="audience_rating_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="enable_credits_marker_generation",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="show",
            name="episode_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="show",
            name="episode_sort",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="show",
            name="flatten_seasons",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="show",
            name="guid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="originally_available_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="season_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="show",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="use_original_title",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="show",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
