# Generated by Django 5.1.1 on 2024-10-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_movie_optimized_art_movie_optimized_poster_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
