# Generated by Django 5.1.1 on 2024-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_movie_content_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="content_rating",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
