# Generated by Django 5.1.1 on 2024-10-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_show_content_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Studio",
                "verbose_name_plural": "Studios",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="art",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="tagline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="art",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="tagline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="trailer_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("photo_url", models.URLField(blank=True, null=True)),
                (
                    "tmdb_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="sync_person_last_na_448009_idx",
                    ),
                    models.Index(
                        fields=["tmdb_id"], name="sync_person_tmdb_id_36bf37_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("ACTOR", "Actor"),
                            ("DIRECTOR", "Director"),
                            ("PRODUCER", "Producer"),
                            ("WRITER", "Writer"),
                            ("CINEMATOGRAPHER", "Cinematographer"),
                            ("COMPOSER", "Composer"),
                            ("EDITOR", "Editor"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "character_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="sync.episode",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="sync.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="sync.person",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="sync.show",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="studio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movies",
                to="sync.studio",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="studio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shows",
                to="sync.studio",
            ),
        ),
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["role_type"], name="sync_role_role_ty_275f5c_idx"
            ),
        ),
    ]
