# Generated by Django 5.1.1 on 2024-10-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0005_episode_absolute_index_episode_added_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="optimized_art",
            field=models.ImageField(blank=True, null=True, upload_to="optimized_art/"),
        ),
        migrations.AddField(
            model_name="movie",
            name="optimized_poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="optimized_posters/"
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="optimized_art",
            field=models.ImageField(blank=True, null=True, upload_to="optimized_art/"),
        ),
        migrations.AddField(
            model_name="show",
            name="optimized_poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="optimized_posters/"
            ),
        ),
    ]
